name: 🔒 Validate Secrets

on: [workflow_dispatch]   # manual trigger only

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret keys (masked)
        run: |
          echo "USERNAME_GITHUB = $USERNAME_GITHUB"
          echo "TOKEN_GITHUB     = $TOKEN_GITHUB"
          echo "REPO_GITHUB      = $REPO_GITHUB"
          echo "USER_EMAIL_GITHUB = $USER_EMAIL_GITHUB"
        env:
          USERNAME_GITHUB:   ${{ secrets.USERNAME_GITHUB }}
          TOKEN_GITHUB:      ${{ secrets.TOKEN_GITHUB }}
          REPO_GITHUB:       ${{ secrets.REPO_GITHUB }}
          USER_EMAIL_GITHUB: ${{ secrets.USER_EMAIL_GITHUB }}
