name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 7
          keep_minimum_runs: 3
